// Generated by eve. Do not edit by hand.
import { loadFrameworkProgrammaticModule as loadProgrammaticModule, memoizeModuleNamespaceFactories } from "eve/internal/programmatic-source-loader";
import * as imported_module_0 from "../../agent/agent.ts";
import * as imported_module_1 from "../../agent/channels/web.ts";
import * as imported_module_12 from "../../agent/tools/search_knowledge.ts";

const module_0 = memoizeModuleNamespaceFactories(imported_module_0);
const module_1 = memoizeModuleNamespaceFactories(imported_module_1);
const module_2 = await loadProgrammaticModule({"kind":"programmatic","moduleId":"sandbox.ts","registryId":"eve:defaults","revision":"eve@0.49.0:compiled-manifest-v46","semanticRevision":"eve:default-sandbox:v1"}, Object.freeze({}));
const module_3 = await loadProgrammaticModule({"kind":"programmatic","moduleId":"tools/bash.ts","registryId":"eve:defaults","revision":"eve@0.49.0:compiled-manifest-v46"}, Object.freeze({}));
const module_4 = await loadProgrammaticModule({"kind":"programmatic","moduleId":"tools/connection_search.ts","registryId":"eve:defaults","revision":"eve@0.49.0:compiled-manifest-v46"}, Object.freeze({}));
const module_5 = await loadProgrammaticModule({"kind":"programmatic","moduleId":"tools/load_skill.ts","registryId":"eve:defaults","revision":"eve@0.49.0:compiled-manifest-v46"}, Object.freeze({}));
const module_6 = await loadProgrammaticModule({"kind":"programmatic","moduleId":"tools/read_file.ts","registryId":"eve:defaults","revision":"eve@0.49.0:compiled-manifest-v46"}, Object.freeze({}));
const module_7 = await loadProgrammaticModule({"kind":"programmatic","moduleId":"tools/todo.ts","registryId":"eve:defaults","revision":"eve@0.49.0:compiled-manifest-v46"}, Object.freeze({}));
const module_8 = await loadProgrammaticModule({"kind":"programmatic","moduleId":"tools/web_fetch.ts","registryId":"eve:defaults","revision":"eve@0.49.0:compiled-manifest-v46"}, Object.freeze({}));
const module_9 = await loadProgrammaticModule({"kind":"programmatic","moduleId":"tools/write_file.ts","registryId":"eve:defaults","revision":"eve@0.49.0:compiled-manifest-v46"}, Object.freeze({}));
const module_10 = await loadProgrammaticModule({"kind":"programmatic","moduleId":"channels/eve.ts","registryId":"eve:root-defaults","revision":"eve@0.49.0:compiled-manifest-v46"}, Object.freeze({}));
const module_11 = await loadProgrammaticModule({"kind":"programmatic","moduleId":"channels/home.ts","registryId":"eve:root-defaults","revision":"eve@0.49.0:compiled-manifest-v46"}, Object.freeze({}));
const module_12 = memoizeModuleNamespaceFactories(imported_module_12);

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/web.ts": module_1,
                  "eve:defaults:sandbox.ts": module_2,
                  "eve:defaults:tools/bash.ts": module_3,
                  "eve:defaults:tools/connection_search.ts": module_4,
                  "eve:defaults:tools/load_skill.ts": module_5,
                  "eve:defaults:tools/read_file.ts": module_6,
                  "eve:defaults:tools/todo.ts": module_7,
                  "eve:defaults:tools/web_fetch.ts": module_8,
                  "eve:defaults:tools/write_file.ts": module_9,
                  "eve:root-defaults:channels/eve.ts": module_10,
                  "eve:root-defaults:channels/home.ts": module_11,
                  "tools/search_knowledge.ts": module_12
                })
            })
    })
});

export default moduleMap;
